version: '3.7'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - '${LOCALSTACK_PORT}:${LOCALSTACK_PORT}'
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=${AWS_SQS_REGION}
      - EDGE_PORT=${LOCALSTACK_PORT}
      - DEBUG=${LOCALSTACK_DEBUG- }
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './scripts/sqs-local-setup.sh:/etc/localstack/init/ready.d/sqs-local-setup.sh'